package line

import (
	"net/http"

	"github.com/albert-einshutoin/mockport/internal/adapter"
)

func (a Adapter) Metadata() adapter.Metadata {
	scenarios := []adapter.Scenario{
		{Name: "line_success", Supported: true},
		{Name: "auth_error", Supported: true},
		{Name: "rate_limited", Supported: true},
		{Name: "invalid_request", Supported: true},
		{Name: "pay_failed", Supported: true},
	}
	return adapter.Metadata{
		Name:            "line",
		Maturity:        adapter.MaturityWorkflowCompatible,
		ProviderVersion: "Messaging API v2 / Login v2.1 / Pay v3 / MINI App service messages / Mini Dapp SDK",
		Levels:          []adapter.Level{adapter.LevelWire, adapter.LevelWorkflow, adapter.LevelState, adapter.LevelError},
		Capabilities: []string{
			"channel_access_token",
			"messaging_bot_info",
			"messaging_content",
			"messaging_group_room",
			"messaging_mark_as_read",
			"messaging_multicast_broadcast_narrowcast",
			"messaging_push",
			"messaging_quota_delivery",
			"messaging_reply",
			"messaging_profile",
			"messaging_rich_menu",
			"messaging_webhook_delivery",
			"messaging_webhook_settings",
			"login_oauth",
			"login_profile",
			"liff_profile",
			"mini_app_service_messages",
			"line_pay_request_confirm",
			"mini_dapp_wallet_payment",
		},
		Scenarios: scenarios,
		StatefulResources: []string{
			"message",
			"oauth_code",
			"oauth_token",
			"rich_menu",
			"rich_menu_alias",
			"user_rich_menu",
			"notification_token",
			"line_pay_payment",
			"mini_dapp_payment",
		},
		Reset: true,
		Endpoints: []adapter.Endpoint{
			{Method: http.MethodPost, Path: "/line/v2/bot/message/push", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request"}, Notes: "LINE Messaging API-like push message"},
			{Method: http.MethodPost, Path: "/line/v2/bot/message/reply", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request"}, Notes: "LINE Messaging API-like reply message"},
			{Method: http.MethodPost, Path: "/line/v2/bot/message/multicast", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request"}, Notes: "LINE Messaging API-like multicast message"},
			{Method: http.MethodPost, Path: "/line/v2/bot/message/broadcast", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request"}, Notes: "LINE Messaging API-like broadcast message"},
			{Method: http.MethodPost, Path: "/line/v2/bot/message/narrowcast", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request"}, Notes: "LINE Messaging API-like narrowcast acceptance"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/progress/narrowcast", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like narrowcast progress"},
			{Method: http.MethodPost, Path: "/line/v2/bot/message/validate/{type}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like message object validation"},
			{Method: http.MethodPost, Path: "/line/v2/bot/chat/markAsRead", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like mark-as-read acknowledgement"},
			{Method: http.MethodPost, Path: "/line/v2/bot/chat/loading/start", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like loading animation acknowledgement"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/{messageId}/content", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like binary content download"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/{messageId}/content/transcoding", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like content transcoding status"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/{messageId}/content/preview", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like content preview download"},
			{Method: http.MethodGet, Path: "/line/v2/bot/profile/{userId}", SupportedScenarios: []string{"line_success", "auth_error"}, Notes: "LINE Messaging API-like user profile"},
			{Method: http.MethodPut, Path: "/line/v2/bot/channel/webhook/endpoint", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like webhook endpoint update"},
			{Method: http.MethodGet, Path: "/line/v2/bot/channel/webhook/endpoint", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like webhook endpoint lookup"},
			{Method: http.MethodPost, Path: "/line/v2/bot/channel/webhook/test", SupportedScenarios: []string{"line_success", "auth_error"}, Notes: "LINE Messaging API-like webhook test"},
			{Method: http.MethodPost, Path: "/line/test/webhook/send", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "Sends a fake LINE signed webhook to the configured target"},
			{Method: http.MethodGet, Path: "/line/v2/bot/info", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like bot information"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/quota", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like quota lookup"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/quota/consumption", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like quota consumption lookup"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/delivery/{type}", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like delivery statistics"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/aggregation/info", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like aggregation unit summary"},
			{Method: http.MethodGet, Path: "/line/v2/bot/message/aggregation/list", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like aggregation unit list"},
			{Method: http.MethodGet, Path: "/line/v2/bot/followers/ids", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like follower IDs"},
			{Method: http.MethodGet, Path: "/line/v2/bot/group/{groupId}/summary", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like group summary"},
			{Method: http.MethodGet, Path: "/line/v2/bot/group/{groupId}/members/ids", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like group member IDs"},
			{Method: http.MethodGet, Path: "/line/v2/bot/group/{groupId}/member/{userId}", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like group member profile"},
			{Method: http.MethodPost, Path: "/line/v2/bot/group/{groupId}/leave", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like group leave acknowledgement"},
			{Method: http.MethodGet, Path: "/line/v2/bot/room/{roomId}/members/ids", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like room member IDs"},
			{Method: http.MethodGet, Path: "/line/v2/bot/room/{roomId}/member/{userId}", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like room member profile"},
			{Method: http.MethodPost, Path: "/line/v2/bot/room/{roomId}/leave", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like room leave acknowledgement"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu creation"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/validate", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu validation"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/list", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like rich menu list"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/{richMenuId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu lookup"},
			{Method: http.MethodDelete, Path: "/line/v2/bot/richmenu/{richMenuId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu deletion"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/{richMenuId}/content", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu image upload"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/{richMenuId}/content", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu image download"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/alias", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu alias creation"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/alias/list", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like rich menu alias list"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/alias/{aliasId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu alias lookup"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/alias/{aliasId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu alias update"},
			{Method: http.MethodDelete, Path: "/line/v2/bot/richmenu/alias/{aliasId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like rich menu alias deletion"},
			{Method: http.MethodGet, Path: "/line/v2/bot/richmenu/progress/batch", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like rich menu batch progress"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/bulk/link", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like bulk rich menu link acknowledgement"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/bulk/unlink", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like bulk rich menu unlink acknowledgement"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/batch", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like rich menu batch acknowledgement"},
			{Method: http.MethodPost, Path: "/line/v2/bot/richmenu/validate/batch", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like rich menu batch validation"},
			{Method: http.MethodPost, Path: "/line/v2/bot/user/all/richmenu/{richMenuId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like default rich menu link"},
			{Method: http.MethodGet, Path: "/line/v2/bot/user/all/richmenu", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like default rich menu lookup"},
			{Method: http.MethodDelete, Path: "/line/v2/bot/user/all/richmenu", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like default rich menu unlink"},
			{Method: http.MethodPost, Path: "/line/v2/bot/user/{userId}/richmenu/{richMenuId}", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like user rich menu link"},
			{Method: http.MethodGet, Path: "/line/v2/bot/user/{userId}/richmenu", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Messaging API-like user rich menu lookup"},
			{Method: http.MethodDelete, Path: "/line/v2/bot/user/{userId}/richmenu", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like user rich menu unlink"},
			{Method: http.MethodPost, Path: "/line/v2/bot/user/{userId}/linkToken", SupportedScenarios: []string{"line_success"}, Notes: "LINE Messaging API-like account link token issue"},
			{Method: http.MethodGet, Path: "/line/oauth2/v2.1/authorize", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE Login-like authorization redirect"},
			{Method: http.MethodPost, Path: "/line/oauth2/v2.1/token", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "LINE Login-like token exchange"},
			{Method: http.MethodGet, Path: "/line/oauth2/v2.1/verify", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE channel access token v2.1-like verification"},
			{Method: http.MethodGet, Path: "/line/oauth2/v2.1/tokens/kid", SupportedScenarios: []string{"line_success"}, Notes: "LINE channel access token v2.1-like key ID list"},
			{Method: http.MethodPost, Path: "/line/oauth2/v2.1/revoke", SupportedScenarios: []string{"line_success"}, Notes: "LINE channel access token v2.1-like revocation"},
			{Method: http.MethodPost, Path: "/line/oauth2/v3/token", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "LINE stateless channel access token-like issue"},
			{Method: http.MethodPost, Path: "/line/v2/oauth/accessToken", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "LINE short-lived channel access token-like issue"},
			{Method: http.MethodPost, Path: "/line/v2/oauth/verify", SupportedScenarios: []string{"line_success", "invalid_request"}, Notes: "LINE short-lived channel access token-like verification"},
			{Method: http.MethodPost, Path: "/line/v2/oauth/revoke", SupportedScenarios: []string{"line_success"}, Notes: "LINE short-lived channel access token-like revocation"},
			{Method: http.MethodGet, Path: "/line/v2/profile", SupportedScenarios: []string{"line_success", "auth_error"}, Notes: "LINE Login-like profile endpoint"},
			{Method: http.MethodGet, Path: "/line/liff/v2/profile", SupportedScenarios: []string{"line_success", "auth_error"}, Notes: "LIFF profile helper for local app tests"},
			{Method: http.MethodGet, Path: "/line/liff/v2/context", SupportedScenarios: []string{"line_success"}, Notes: "LIFF context helper for local app tests"},
			{Method: http.MethodPost, Path: "/line/test/reset", SupportedScenarios: []string{"line_success", "auth_error", "rate_limited", "invalid_request", "pay_failed"}, Notes: "Clears state for test isolation"},
			{Method: http.MethodPost, Path: "/line/message/v3/notifier/token", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "LINE MINI App Service Message API-like notification token issue"},
			{Method: http.MethodPost, Path: "/line/message/v3/notifier/send", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "LINE MINI App Service Message API-like send"},
			{Method: http.MethodPost, Path: "/line/v3/payments/request", SupportedScenarios: []string{"line_success", "auth_error", "pay_failed", "invalid_request"}, Notes: "LINE Pay v3-like payment request"},
			{Method: http.MethodPost, Path: "/line/v3/payments/{transactionId}/confirm", SupportedScenarios: []string{"line_success", "auth_error", "pay_failed"}, Notes: "LINE Pay v3-like payment confirm"},
			{Method: http.MethodGet, Path: "/line/v3/payments/requests/{transactionId}/check", SupportedScenarios: []string{"line_success", "pay_failed"}, Notes: "LINE Pay v3-like payment request status"},
			{Method: http.MethodPost, Path: "/line/mini-dapp/v1/wallet/sessions", SupportedScenarios: []string{"line_success", "auth_error", "invalid_request"}, Notes: "Mini Dapp wallet session helper"},
			{Method: http.MethodPost, Path: "/line/mini-dapp/v1/payments", SupportedScenarios: []string{"line_success", "auth_error", "pay_failed", "invalid_request"}, Notes: "Mini Dapp SDK-like payment helper"},
			{Method: http.MethodGet, Path: "/line/mini-dapp/v1/payments/{id}", SupportedScenarios: []string{"line_success", "pay_failed"}, Notes: "Mini Dapp SDK-like payment lookup"},
		},
	}
}
