package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

const defaultMockportYAML = `version: "0.1"

server:
  host: 0.0.0.0
  port: 43101

mode: ai-safe

adapters:
  stripe:
    enabled: true
    base_path: /stripe
    scenario: payment_success
    fake_secret: mockport_stripe_secret
    webhook:
      target_url: http://app:3000/webhooks/stripe
      signing_secret: whsec_mockport
`

const defaultEnvMockport = `# Generated by Mockport. Safe for local and CI use.

STRIPE_API_URL=http://localhost:43101/stripe
STRIPE_SECRET_KEY=mockport_stripe_secret
STRIPE_WEBHOOK_SECRET=whsec_mockport
`

const defaultCompose = `services:
  mockport:
    image: ghcr.io/albert-einshutoin/mockport:latest
    ports:
      - "43101:43101"
    volumes:
      - ./mockport.yml:/etc/mockport/mockport.yml
`

func newInitCommand() *cobra.Command {
	var adapterName string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate Mockport local files",
		RunE: func(cmd *cobra.Command, args []string) error {
			if adapterName != "stripe" {
				return fmt.Errorf("unsupported adapter %q: minimal MVP supports stripe", adapterName)
			}
			files := map[string]string{
				"mockport.yml":                defaultMockportYAML,
				".env.mockport":               defaultEnvMockport,
				"docker-compose.mockport.yml": defaultCompose,
			}
			for path, content := range files {
				if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
					return fmt.Errorf("write %s: %w", path, err)
				}
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Generated mockport.yml, .env.mockport, docker-compose.mockport.yml")
			return nil
		},
	}
	cmd.Flags().StringVar(&adapterName, "adapter", "stripe", "Adapter to initialize")
	return cmd
}
